# Generated by Django 3.1.7 on 2021-03-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hosp_estimates',
            new_name='hosp_est',
        ),
        migrations.RenameModel(
            old_name='hosp_requirements',
            new_name='hosp_req',
        ),
    ]
