# Generated by Django 3.1.7 on 2021-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hosp_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosp_emp',
            name='department',
        ),
        migrations.AddField(
            model_name='hosp_emp',
            name='hospital',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=10),
        ),
    ]
