# Generated by Django 3.1.7 on 2021-03-18 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210309_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosp_est',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 15, 59, 1, 968590, tzinfo=utc), verbose_name='Date of record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosp_req',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 15, 59, 14, 96609, tzinfo=utc), verbose_name='Date of change'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hosp_inv',
            unique_together={('itemname', 'quantity', 'hosp_name')},
        ),
    ]
