# Generated by Django 3.1.7 on 2021-03-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_delete_hosp_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='supp_inv',
            fields=[
                ('supp_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('E', 'E')], max_length=10, primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(verbose_name='Inventory date')),
            ],
        ),
        migrations.CreateModel(
            name='supp_storage',
            fields=[
                ('supp_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('E', 'E')], max_length=10, primary_key=True, serialize=False)),
                ('maximum', models.IntegerField()),
                ('occupied', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='hosp_est',
        ),
        migrations.AlterUniqueTogether(
            name='hosp_inv',
            unique_together={('itemname', 'hosp_name')},
        ),
        migrations.AlterUniqueTogether(
            name='hosp_req',
            unique_together={('itemname', 'hosp_name', 'date')},
        ),
    ]
