# Generated by Django 3.1.7 on 2021-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20210330_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='supp_inv',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supp_inv',
            name='supp_name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('E', 'E')], max_length=10),
        ),
    ]
