# Generated by Django 3.1.7 on 2021-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20210330_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='supp_inv',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
