# Generated by Django 3.1.7 on 2021-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_supp_inv_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='drug_class',
            fields=[
                ('drugname', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='hosp_inv',
            name='hosp_name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hosp_req',
            name='hosp_name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=10),
        ),
    ]
