# Generated by Django 3.1.7 on 2021-04-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20210331_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='manuf_making',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_name', models.CharField(choices=[('D', 'D'), ('G', 'G')], max_length=10)),
                ('itemname', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('date_of_production', models.DateField()),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='drug_class',
        ),
    ]
